---
title: "Data Mining Challange: Resoures"
author: "Pietro Monticone"
date: "`r Sys.Date()` | Turin University"
output:
 prettydoc::html_pretty:
    theme: cayman
    highlight: github
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
``` 

# Data Camp

## Theory
* [Data Science for Everyone](https://www.datacamp.com/courses/data-science-for-everyone)
* [Machine Learning for Everyone](https://www.datacamp.com/courses/machine-learning-for-everyone)

## Python 

### Programming
* [Introduction to Python](https://www.datacamp.com/courses/intro-to-python-for-data-science)
* [Intermediate Python](https://www.datacamp.com/courses/intermediate-python)
* [Data Science Toolbox 1](https://www.datacamp.com/courses/python-data-science-toolbox-part-1)
* [Data Science Toolbox 2](https://www.datacamp.com/courses/python-data-science-toolbox-part-2)

#### Coding Best Practices with Python
* [Writing Efficient Python Code](https://www.datacamp.com/courses/writing-efficient-python-code)
* [Writing Efficient Code with pandas](https://www.datacamp.com/courses/writing-efficient-code-with-pandas)
* [Writing Funcitons in Python](https://www.datacamp.com/courses/writing-functions-in-python)
* [Object-Oriented Programming in Python](https://www.datacamp.com/courses/object-oriented-programming-in-python)

### Data Collection & Cleaning

* [Introduction](https://www.datacamp.com/courses/introduction-to-importing-data-in-python)
* [Intermediate](https://www.datacamp.com/courses/intermediate-importing-data-in-python)
* [Cleaning](https://www.datacamp.com/courses/cleaning-data-in-python)

### Data Manipulation 
* [pandas Foundations](https://www.datacamp.com/courses/pandas-foundations)
* [Manipulating DataFrames with pandas](https://www.datacamp.com/courses/manipulating-dataframes-with-pandas)
* [Merging DataFrames with pandas](https://www.datacamp.com/courses/merging-dataframes-with-pandas)

### Data Visualization
* [Introduction to Data Viz with Matplotlib](https://www.datacamp.com/courses/introduction-to-data-visualization-with-matplotlib)
* [Introduction to Data Viz with Seaborn](https://www.datacamp.com/courses/introduction-to-data-visualization-with-seaborn)
* [Improving Data Viz)(https://www.datacamp.com/courses/improving-your-data-visualizations-in-python)
* [Interactive Data Viz](https://www.datacamp.com/courses/interactive-data-visualization-with-bokeh)

### Machine Learning 
* [Supervised Learning with scikit-learn](https://www.datacamp.com/courses/supervised-learning-with-scikit-learn)
* [Unsupervised Learning in Python](https://www.datacamp.com/courses/unsupervised-learning-in-python)
* [Linear Classifiers in Python](https://www.datacamp.com/courses/linear-classifiers-in-python)

#### NLP
* [Introduction to Natural Language Processing in Python](https://www.datacamp.com/courses/introduction-to-natural-language-processing-in-python)
* [Advanced NLP with spaCy](https://learn.datacamp.com/courses/advanced-nlp-with-spacy)

# Kaggle 
* Python 
* Bag of words 

# Notebooks 

# Github 
* **2018** [Project by Simone Azeglio](https://github.com/simoneazeglio/DataMiningChallenge2018)

# Lectures 

## MIT

* **2020**[6.S191: Introduction to
Deep Learning](http://introtodeeplearning.com)


## Caltech 

## Stanford

* **2020** [CS224n: Natural Language Processing with Deep Learning](http://web.stanford.edu/class/cs224n/index.html)
* **2019** [CS224n: Natural Language Processing with Deep Learning](https://web.stanford.edu/class/archive/cs/cs224n/cs224n.1194/)

## 3B1B 
* [Neural Networks](https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi)
